spring:
  liquibase:
    enabled: false
  application:
    name: FoodRu_MicroService
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/food_db
    username: postgres
    password: postgres
    poolName: myPool
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.yandex.ru
    port: 587
    username: daniil.glovatsky@yandex.ru
    password: hngnlwgjftlauomk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  s3:
    serviceEndpoint: https://storage.yandexcloud.net
    signingRegion: ru-central1
    bucketName: bucket-for-s3
    accessKeyId: YCAJE0sU1RpxZtayJhor-EAg3
    secretAccessKey: YCPGq37wBlm2LlC0k35_qwqncdf0RROs5FTtKAKo

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: myGroup
  properties:
    kafka:
      bootstrapAddress: localhost:29092
      topicEdadilToFoodRu: topicEdadilToFoodRu
      topicFoodRuToEdadil: topicFoodRuToEdadil
server:
  port: 7070