spring:
  application:
    name: Authentication_Service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5437/registration_db?stringtype=unspecified
    username: postgres
    password: postgres
    poolName: myPool

jwt:
  secret: ${JWT_TOKEN}

server:
  port: 1010

duration:
  shortTime: 10
  longTime: 43200

