spring:
  application:
    name: Edadil_MicroService
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/edadil_db
    username: postgres
    password: postgres
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 10

  properties:
    kafka:
      bootstrapAddress: localhost:29092
      topicEdadilToFoodRu: topicEdadilToFoodRu
      topicFoodRuToEdadil: topicFoodRuToEdadil
      groupId: edadilGroup

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true



server:
  port: 4040

springdoc:
  api-docs:
    path: /v3/edadil-api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config


