spring:
  application:
    name: Edadil_MicroService

database:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/edadil_db
    username: ${username}
    password: ${password}




server:
  port: 4040

