spring:
  application:
    name: Edadil_MicroService
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5433/edadil_db
    username: postgres
    password: postgres
    poolName: myPool

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true



server:
  port: 4040

