name: CI/edadil

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - for_testing
  pull_request:
    branches:
      - master
      - for_testing
    paths:
      - .github/workflows/edadil.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: cd Edadil_MicroService && mvn clean install

      - name: Run tests
        run: cd Edadil_MicroService && mvn test


      - name: Calculate test coverage
        run: cd Edadil_MicroService && mvn jacoco:report

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/lesam19092/edadil:latest Edadil_MicroService  # Tag for GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}


      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: Edadil_MicroService/target/site/jacoco/jacoco.xml

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/lesam19092/edadil:latest

      - name: Verify Docker image
        run: docker images ghcr.io/lesam19092/edadil:latest
